# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-11 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=30, verbose_name='Задание')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('complete_date', models.DateTimeField(auto_now=True)),
                ('done', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Задания',
                'verbose_name': 'Задание',
            },
        ),
    ]
